= Home

Welcome to the Vy Developer Portal!
Here you can find a variety of information about our APIs and how to use them.

[.panel]
== xref:services.adoc[]

A comprehensive list of all services available for use.
This gives you a complete overview over the services and their endpoints.

[.panel]
== xref:authentication.adoc[]

Learn how to authenticate with xref:services.adoc[our services] by using OAuth!

== Learn more about the services

Additional resources can also be found to learn more about our services and their status.

[.grid]
link:https://vy.statuspage.io/[Statuspage]::
An overview of the curent and past operational status of our services.

link:https://vygruppen.atlassian.net/wiki/spaces/VyDev/pages/3636174855/Organisering+av+utvikling[Team Overview]::
See which teams Vy have and who are a member of these teams.
This is an internal resource, and requires a Vy user.

link:https://vygruppen.atlassian.net/wiki/spaces/INFRA/pages/6379864114/Service+Overview[Service Overview]::
Service overview with details about ownership, contact information and service information

link:https://grafana.common-services.vydev.io/d/3iL1YHtnk/pipeline-metrics-overview?orgId=1[DORA metrics]::
Overview of release metrics inregards to service updates



